// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhzzCg88t5hRzw040HKE3eqvXO-9-bqtM',
    appId: '1:313180797580:web:12976de3675e34ff7559a9',
    messagingSenderId: '313180797580',
    projectId: 'brukwaya-note',
    authDomain: 'brukwaya-note.firebaseapp.com',
    storageBucket: 'brukwaya-note.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWJRgNmi0Q_TWHX2Xm6xNozgNNYq-1rY8',
    appId: '1:313180797580:android:c0c566b1c23ab5b57559a9',
    messagingSenderId: '313180797580',
    projectId: 'brukwaya-note',
    storageBucket: 'brukwaya-note.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp5u7LnP7GfbDFsTa-1Sj909wXEq4fdMs',
    appId: '1:313180797580:ios:00f7d4007e520c357559a9',
    messagingSenderId: '313180797580',
    projectId: 'brukwaya-note',
    storageBucket: 'brukwaya-note.firebasestorage.app',
    iosBundleId: 'com.yourcompany.notepadApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhzzCg88t5hRzw040HKE3eqvXO-9-bqtM',
    appId: '1:313180797580:web:a4fea3ad9962a2b27559a9',
    messagingSenderId: '313180797580',
    projectId: 'brukwaya-note',
    authDomain: 'brukwaya-note.firebaseapp.com',
    storageBucket: 'brukwaya-note.firebasestorage.app',
  );
}
